### ISSUE TITLE
Does this support django 2?

### ISSUE THREAD

**Issue by eric0324** [Olorin92/django_cognito#1]
Does this support django 2?

How can I use it? Do you have any documents??

**Comment by Olorin92** [comment]
Hi there @eric0324,

Sorry for my very delayed response - I've been a bit lax in keeping this library up to date. 

I haven't tested with Django 2, but it should work providing there weren't any major changes around the way it implements the authentication middleware.

I'm working on providing some more detailed documentation that should help guide on how to implement this in a Django project.
